title: hermitmaster
description:
show_downloads: false
google_analytics:

contact:
  - display: hermitmaster@icloud.com
    url: mailto:hermitmaster@icloud.com
  - display: LinkedIn
    url: https://linkedin.com/in/hermitmaster
  - display: GitHub
    url: https://github.com/hermitmaster
nav:
  - title: Blog
    url: /blog.html
  - title: Resume
    url: /resume
